name: Contracts CI

on:
  push:
    paths:
      - "contracts/**"
  pull_request:
    paths:
      - "contracts/**"

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
      - run: cargo check
